# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deep_reinforcement_learning_hands_on',
                'doc_host': 'https://MeherKharbachi.github.io',
                'git_url': 'https://github.com/MeherKharbachi/deep_reinforcement_learning_hands_on',
                'lib_path': 'deep_reinforcement_learning_hands_on'},
  'syms': { 'deep_reinforcement_learning_hands_on.core': { 'deep_reinforcement_learning_hands_on.core.foo': ( 'core.html#foo',
                                                                                                              'deep_reinforcement_learning_hands_on/core.py')}}}
